[package]
name = "bbphysic_wasm"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[profile.release]
opt-level = "z"
lto = true
codegen-units = 1
panic = "abort"

[dependencies]

# Physics / collision queries (used as a robust broad-phase + narrow-phase for baked collisions)
rapier3d = { version = "0.18", default-features = false, features = ["dim3", "f32"] }
